import { defaultName, maptilerNameExpression } from './voyage'

export default function natureStyle(
	key,
	nameExpression = maptilerNameExpression,
	name = defaultName
) {
	return {
		version: 8,
		id: 'carte-nature', // forked from maptiler's topo-v2
		name: 'Nature',
		sources: {
			contours: {
				url: `https://api.maptiler.com/tiles/contours/tiles.json?key=${key}`,
				type: 'vector',
			},
			'gel-raster-dem': {
				tiles: [
					'pmtiles://https://data.source.coop/smartmaps/gel/gel.pmtiles/{z}/{x}/{y}.webp',
				],
				type: 'raster-dem',
				tileSize: 512,
				minzoom: 2,
				maxzoom: 12,
			},
			maptiler_planet: {
				url: `https://api.maptiler.com/tiles/v3/tiles.json?key=${key}`,
				type: 'vector',
			},
			maptiler_attribution: {
				attribution:
					'<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
				type: 'vector',
			},
		},
		layers: [
			{
				id: 'Background',
				type: 'background',
				minzoom: 0,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'background-color': 'hsl(0,0%,93%)',
				},
			},
			{
				id: 'Glacier',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landcover',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(0,0%,100%)',
					'fill-opacity': 1,
					'fill-antialias': false,
				},
				metadata: {},
				filter: ['==', 'class', 'ice'],
			},
			{
				id: 'Crop',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'globallandcover',
				maxzoom: 8,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(51, 34%, 85%)',
					'fill-opacity': {
						stops: [
							[0, 1],
							[8, 0.1],
						],
					},
					'fill-antialias': true,
				},
				filter: ['==', 'class', 'crop'],
			},
			{
				id: 'Scrub',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'globallandcover',
				maxzoom: 8,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(75, 37%, 75%)',
					'fill-opacity': {
						stops: [
							[0, 1],
							[8, 0.1],
						],
					},
					'fill-antialias': true,
				},
				filter: ['==', 'class', 'scrub'],
			},
			{
				id: 'Forest',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'globallandcover',
				maxzoom: 8,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(74,31%,70%)',
					'fill-antialias': true,
				},
				filter: ['in', 'class', 'forest', 'tree'],
			},
			{
				id: 'Residential',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landuse',
				maxzoom: 16,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(45,14%,71%)',
					'fill-opacity': {
						stops: [
							[4, 0.6],
							[16, 0.1],
						],
					},
				},
				filter: [
					'all',
					['==', '$type', 'Polygon'],
					['in', 'class', 'residential', 'suburb', 'neighbourhood'],
				],
			},
			{
				id: 'Industrial',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landuse',
				minzoom: 10,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': {
						stops: [
							[12, 'hsl(0,0%,70%)'],
							[16, 'hsl(47,16%,89%)'],
						],
					},
					'fill-opacity': 0.5,
				},
				metadata: {},
				filter: ['in', 'class', 'industrial', 'commercial', 'retail'],
			},
			{
				id: 'Pedestrian',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(43,25%,99%)',
					'fill-opacity': 0.5,
				},
				metadata: {},
				filter: [
					'all',
					['==', '$type', 'Polygon'],
					['!has', 'brunnel'],
					['!in', 'class', 'bridge', 'pier'],
					['in', 'subclass', 'pedestrian', 'platform'],
				],
			},
			{
				id: 'Dam',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landuse',
				minzoom: 9,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(69, 20%, 79%)',
					'fill-opacity': {
						stops: [
							[9, 0.25],
							[16, 1],
						],
					},
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['==', 'class', 'dam'],
			},
			{
				id: 'Garages',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landuse',
				minzoom: 9,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(0, 0%, 93%)',
					'fill-opacity': {
						stops: [
							[9, 0.25],
							[16, 1],
						],
					},
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['==', 'class', 'garages'],
			},
			{
				id: 'Cemetery',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landuse',
				minzoom: 9,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(0, 0%, 76%)',
					'fill-opacity': {
						stops: [
							[9, 0.25],
							[16, 1],
						],
					},
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['==', 'class', 'cemetery'],
			},
			{
				id: 'Hospital',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landuse',
				minzoom: 9,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(325, 26%, 91%)',
					'fill-opacity': {
						stops: [
							[9, 0.25],
							[16, 1],
						],
					},
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['==', 'class', 'hospital'],
			},
			{
				id: 'Stadium',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landuse',
				minzoom: 9,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(90, 49%, 70%)',
					'fill-opacity': {
						stops: [
							[9, 0.25],
							[16, 1],
						],
					},
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['in', 'class', 'pitch', 'stadium'],
			},
			{
				id: 'Wood',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landcover',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(74, 31%, 70%)',
					'fill-opacity': 1,
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['==', 'class', 'wood'],
			},
			{
				id: 'Grass',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landcover',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(79, 35%, 81%)',
					'fill-opacity': 1,
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['==', 'class', 'grass'],
			},
			{
				id: 'Sand',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'landcover',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(54, 93%, 83%)',
					'fill-opacity': 1,
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['==', 'class', 'sand'],
			},
			{
				id: 'Hillshade',
				type: 'hillshade',
				source: 'gel-raster-dem',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'hillshade-accent-color': 'hsl(51, 30%, 79%)',
					'hillshade-shadow-color': 'hsl(0, 0%, 50%)',
					'hillshade-highlight-color': 'hsl(0, 0%, 83%)',
				},
			},
			{
				id: 'Contour index',
				type: 'line',
				source: 'contours',
				'source-layer': 'contour',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(22, 35%, 55%)',
					'line-width': 1.3,
					'line-opacity': {
						stops: [
							[7, 0.2],
							[10, 0.6],
						],
					},
				},
				filter: ['all', ['in', 'nth_line', 5, 10], ['!has', 'glacier']],
			},
			{
				id: 'Glacier contour index',
				type: 'line',
				source: 'contours',
				'source-layer': 'contour',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(192, 85%, 54%)',
					'line-width': 1.3,
					'line-opacity': {
						stops: [
							[7, 0.2],
							[10, 0.6],
						],
					},
				},
				filter: ['all', ['in', 'nth_line', 5, 10], ['==', 'glacier', 1]],
			},
			{
				id: 'Contour',
				type: 'line',
				source: 'contours',
				'source-layer': 'contour',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(22, 35%, 55%)',
					'line-width': 0.8,
					'line-opacity': 0.5,
				},
				filter: ['all', ['!in', 'nth_line', 5, 10], ['!has', 'glacier']],
			},
			{
				id: 'Glacier contour',
				type: 'line',
				source: 'contours',
				'source-layer': 'contour',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(192, 85%, 54%)',
					'line-width': 0.8,
					'line-opacity': 0.5,
				},
				filter: ['all', ['!in', 'nth_line', 5, 10], ['==', 'glacier', 1]],
			},
			{
				id: 'Contour labels',
				type: 'symbol',
				source: 'contours',
				'source-layer': 'contour',
				layout: {
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': {
						base: 1,
						stops: [
							[15, 9.5],
							[20, 12],
						],
					},
					'text-field': '{height}',
					visibility: 'visible',
					'text-padding': 10,
					'symbol-placement': 'line',
					'symbol-avoid-edges': true,
					'text-allow-overlap': false,
					'text-ignore-placement': false,
					'text-rotation-alignment': 'map',
				},
				paint: {
					'text-color': 'hsl(20, 28%, 32%)',
					'text-halo-blur': 1,
					'text-halo-color': 'hsl(0, 0%, 100%)',
					'text-halo-width': 0.5,
				},
				metadata: {},
				filter: [
					'all',
					['==', '$type', 'LineString'],
					['in', 'nth_line', 10, 5],
					['>', 'height', 0],
					['!=', 'glacier', 1],
				],
			},
			{
				id: 'Glacier contour labels',
				type: 'symbol',
				source: 'contours',
				'source-layer': 'contour',
				layout: {
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': {
						base: 1,
						stops: [
							[15, 9.5],
							[20, 12],
						],
					},
					'text-field': '{height}',
					visibility: 'visible',
					'text-padding': 10,
					'symbol-placement': 'line',
					'symbol-avoid-edges': true,
					'text-allow-overlap': false,
					'text-ignore-placement': false,
					'text-rotation-alignment': 'map',
				},
				paint: {
					'text-color': 'hsl(192, 85%, 38%)',
					'text-halo-blur': 1,
					'text-halo-color': 'hsl(0,0%,100%)',
					'text-halo-width': 0.5,
				},
				metadata: {},
				filter: [
					'all',
					['==', '$type', 'LineString'],
					['in', 'nth_line', 10, 5],
					['>', 'height', 0],
					['==', 'glacier', 1],
				],
			},
			{
				id: 'River tunnel',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'waterway',
				minzoom: 14,
				layout: {
					'line-cap': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(199, 44%, 59%)',
					'line-width': {
						base: 1.3,
						stops: [
							[13, 0.5],
							[20, 6],
						],
					},
					'line-dasharray': [2, 4],
				},
				filter: ['==', 'brunnel', 'tunnel'],
			},
			{
				id: 'River',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'waterway',
				layout: {
					'line-cap': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(199, 44%, 59%)',
					'line-width': {
						base: 1.2,
						stops: [
							[11, 1],
							[20, 18],
						],
					},
				},
				metadata: {},
				filter: [
					'all',
					['==', 'class', 'river'],
					['!=', 'brunnel', 'tunnel'],
					['!=', 'intermittent', 1],
				],
			},
			{
				id: 'River intermittent',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'waterway',
				layout: {
					'line-cap': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': {
						stops: [
							[6, 'hsl(199, 44%, 59%)'],
							[8, 'hsl(191, 51%, 85%)'],
							[9, 'hsl(199, 44%, 59%)'],
						],
					},
					'line-width': {
						base: 1.2,
						stops: [
							[11, 1],
							[20, 18],
						],
					},
					'line-dasharray': [2, 1.6],
				},
				metadata: {},
				filter: [
					'all',
					['==', 'class', 'river'],
					['!=', 'brunnel', 'tunnel'],
					['==', 'intermittent', 1],
				],
			},
			{
				id: 'Waterway',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'waterway',
				layout: {
					'line-cap': 'butt',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(199, 44%, 59%)',
					'line-width': {
						base: 1.3,
						stops: [
							[13, 0.5],
							[20, 12],
						],
					},
				},
				metadata: {},
				filter: [
					'all',
					['!=', 'class', 'river'],
					['!=', 'brunnel', 'tunnel'],
					['!=', 'intermittent', 1],
				],
			},
			{
				id: 'Waterway intermittent',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'waterway',
				layout: {
					'line-cap': 'butt',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(199, 44%, 59%)',
					'line-width': {
						base: 1.3,
						stops: [
							[13, 0.5],
							[20, 12],
						],
					},
					'line-dasharray': [4, 3],
				},
				metadata: {},
				filter: [
					'all',
					['!=', 'class', 'river'],
					['!=', 'brunnel', 'tunnel'],
					['==', 'intermittent', 1],
				],
			},
			{
				id: 'Water',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'water',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(199, 44%, 59%)',
				},
				metadata: {},
				filter: ['all', ['!=', 'intermittent', 1], ['!=', 'brunnel', 'tunnel']],
			},
			{
				id: 'Water intermittent',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'water',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(200, 45%, 75%)',
					'fill-opacity': 1,
				},
				metadata: {},
				filter: ['==', 'intermittent', 1],
			},
			{
				id: 'Runway',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'aeroway',
				minzoom: 11,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 100%)',
					'line-width': {
						base: 1.2,
						stops: [
							[11, 3],
							[20, 16],
						],
					},
				},
				metadata: {},
				filter: [
					'all',
					['==', '$type', 'LineString'],
					['==', 'class', 'runway'],
				],
			},
			{
				id: 'Taxiway',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'aeroway',
				minzoom: 11,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 100%)',
					'line-width': {
						base: 1.2,
						stops: [
							[11, 0.5],
							[20, 6],
						],
					},
				},
				metadata: {},
				filter: ['==', 'class', 'taxiway'],
			},
			{
				id: 'Ferry',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 6,
				layout: {
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(201, 59%, 45%)',
					'line-width': {
						stops: [
							[10, 0.5],
							[14, 1.1],
						],
					},
					'line-opacity': [
						'interpolate',
						['linear'],
						['zoom'],
						6,
						0.5,
						7,
						0.8,
						8,
						1,
					],
					'line-dasharray': [2, 2],
				},
				filter: ['==', 'class', 'ferry'],
			},
			{
				id: 'Tunnel outline',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 4,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': [
						'match',
						['get', 'class'],
						'motorway',
						'hsl(28,72%,69%)',
						['trunk', 'primary'],
						'hsl(26, 56%, 68%)',
						'hsl(36,5%,80%)',
					],
					'line-width': [
						'interpolate',
						['linear', 2],
						['zoom'],
						6,
						0,
						7,
						0.5,
						10,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 0, 2.5],
							['trunk', 'primary'],
							2,
							0,
						],
						12,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 2, 6],
							['trunk', 'primary'],
							3,
							['secondary', 'tertiary'],
							2,
							['minor', 'service', 'track'],
							1,
							0.5,
						],
						14,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 5, 8],
							['trunk'],
							4,
							['primary'],
							6,
							['secondary'],
							6,
							['tertiary'],
							4,
							['minor', 'service', 'track'],
							3,
							3,
						],
						16,
						[
							'match',
							['get', 'class'],
							['motorway', 'trunk', 'primary'],
							10,
							['secondary'],
							8,
							['tertiary'],
							8,
							['minor', 'service', 'track'],
							4,
							4,
						],
						20,
						[
							'match',
							['get', 'class'],
							['motorway', 'trunk', 'primary'],
							26,
							['secondary'],
							26,
							['tertiary'],
							26,
							['minor', 'service', 'track'],
							18,
							18,
						],
					],
					'line-dasharray': [0.5, 0.25],
				},
				metadata: {},
				filter: [
					'all',
					['==', 'brunnel', 'tunnel'],
					[
						'!in',
						'class',
						'ferry',
						'rail',
						'transit',
						'pier',
						'bridge',
						'path',
						'aerialway',
						'motorway_construction',
						'trunk_construction',
						'primary_construction',
						'secondary_construction',
						'tertiary_construction',
						'minor_construction',
						'service_construction',
						'track_construction',
					],
				],
			},
			{
				id: 'Tunnel',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 4,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': [
						'match',
						['get', 'class'],
						'motorway',
						'hsl(35, 100%, 76%)',
						['trunk', 'primary'],
						'hsl(46, 100%, 91%)',
						'hsl(0, 0%, 96%)',
					],
					'line-width': [
						'interpolate',
						['linear', 2],
						['zoom'],
						5,
						0,
						6,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'brunnel'], ['bridge'], 0, 1],
							['trunk', 'primary'],
							0,
							0,
						],
						10,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 0, 2.5],
							['trunk', 'primary'],
							1.5,
							1,
						],
						12,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 1, 4],
							['trunk'],
							2.5,
							['primary'],
							2.5,
							['secondary', 'tertiary'],
							1.5,
							['minor', 'service', 'track'],
							1,
							1,
						],
						14,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 5, 6],
							['trunk'],
							3,
							['primary'],
							5,
							['secondary'],
							4,
							['tertiary'],
							3,
							['minor', 'service', 'track'],
							2,
							2,
						],
						16,
						[
							'match',
							['get', 'class'],
							['motorway', 'trunk', 'primary'],
							8,
							['secondary'],
							7,
							['tertiary'],
							6,
							['minor', 'service', 'track'],
							4,
							4,
						],
						20,
						[
							'match',
							['get', 'class'],
							['motorway', 'trunk', 'primary'],
							24,
							['secondary'],
							24,
							['tertiary'],
							24,
							['minor', 'service', 'track'],
							16,
							16,
						],
					],
					'line-opacity': 1,
				},
				metadata: {},
				filter: [
					'all',
					['==', 'brunnel', 'tunnel'],
					[
						'!in',
						'class',
						'ferry',
						'rail',
						'transit',
						'pier',
						'bridge',
						'path',
						'aerialway',
						'motorway_construction',
						'trunk_construction',
						'primary_construction',
						'secondary_construction',
						'tertiary_construction',
						'minor_construction',
						'service_construction',
						'track_construction',
					],
				],
			},
			{
				id: 'Railway tunnel',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0,0%,73%)',
					'line-width': {
						base: 1.4,
						stops: [
							[14, 0.4],
							[15, 0.75],
							[20, 2],
						],
					},
					'line-opacity': 0.5,
				},
				metadata: {},
				filter: ['all', ['==', 'brunnel', 'tunnel'], ['==', 'class', 'rail']],
			},
			{
				id: 'Railway tunnel hatching',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0,0%,73%)',
					'line-width': {
						base: 1.4,
						stops: [
							[14.5, 0],
							[15, 3],
							[20, 8],
						],
					},
					'line-opacity': 0.5,
					'line-dasharray': [0.2, 8],
				},
				metadata: {},
				filter: ['all', ['==', 'brunnel', 'tunnel'], ['==', 'class', 'rail']],
			},
			{
				id: 'Tunnel path',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 12,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsla(0,0%,63%,0.45)',
					'line-width': {
						base: 1.2,
						stops: [
							[14, 0.5],
							[16, 1],
							[18, 2],
							[22, 5],
						],
					},
					'line-opacity': 1,
					'line-dasharray': [3, 2],
				},
				metadata: {},
				filter: ['all', ['==', 'class', 'path'], ['==', 'brunnel', 'tunnel']],
			},
			{
				id: 'Bridge',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsla(42, 49%, 93%, 0.6)',
					'fill-antialias': true,
				},
				metadata: {},
				filter: [
					'all',
					['==', '$type', 'Polygon'],
					['==', 'brunnel', 'bridge'],
				],
			},
			{
				id: 'Pier',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(47, 16%, 89%)',
					'fill-antialias': true,
				},
				metadata: {},
				filter: ['all', ['==', '$type', 'Polygon'], ['==', 'class', 'pier']],
			},
			{
				id: 'Pier road',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					'line-cap': 'round',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(47, 16%, 89%)',
					'line-width': {
						base: 1.2,
						stops: [
							[13, 0.5],
							[15, 1],
							[18, 4],
						],
					},
				},
				metadata: {},
				filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'pier']],
			},
			{
				id: 'Minor road outline',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 10,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(40, 6%, 80%)',
					'line-width': [
						'interpolate',
						['linear', 2],
						['zoom'],
						10,
						0,
						12,
						[
							'match',
							['get', 'class'],
							['secondary', 'tertiary'],
							2,
							['minor', 'service', 'track'],
							1,
							0.7,
						],
						14,
						[
							'match',
							['get', 'class'],
							['secondary'],
							6,
							['tertiary'],
							4,
							['minor', 'service', 'track'],
							3,
							3,
						],
						16,
						[
							'match',
							['get', 'class'],
							['secondary'],
							8,
							['tertiary'],
							8,
							['minor', 'service', 'track'],
							4,
							4,
						],
						20,
						[
							'match',
							['get', 'class'],
							['secondary'],
							26,
							['tertiary'],
							26,
							['minor', 'service', 'track'],
							17,
							17,
						],
					],
					'line-opacity': 1,
				},
				metadata: {},
				filter: [
					'all',
					['!=', 'brunnel', 'tunnel'],
					[
						'!in',
						'class',
						'aerialway',
						'bridge',
						'ferry',
						'minor_construction',
						'motorway',
						'motorway_construction',
						'path',
						'pier',
						'primary',
						'primary_construction',
						'rail',
						'secondary',
						'secondary_construction',
						'service_construction',
						'tertiary_construction',
						'track_construction',
						'transit',
						'trunk',
						'trunk_construction',
					],
				],
			},
			{
				id: 'Major road outline',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 4,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(28, 72%, 69%)',
					'line-width': [
						'interpolate',
						['linear', 2],
						['zoom'],
						6,
						0,
						7,
						0.5,
						10,
						['match', ['get', 'class'], ['trunk', 'primary'], 2.4, 0],
						12,
						['match', ['get', 'class'], ['trunk', 'primary'], 3, 0.7],
						14,
						['match', ['get', 'class'], ['trunk'], 4, ['primary'], 6, 3],
						16,
						['match', ['get', 'class'], ['trunk', 'primary'], 10, 4],
						20,
						['match', ['get', 'class'], ['trunk', 'primary'], 26, 17],
					],
					'line-opacity': 1,
				},
				metadata: {},
				filter: [
					'all',
					['!=', 'brunnel', 'tunnel'],
					['in', 'class', 'primary', 'trunk'],
				],
			},
			{
				id: 'Highway outline',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 4,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(25, 75%, 61%)',
					'line-width': [
						'interpolate',
						['linear', 2],
						['zoom'],
						6,
						0,
						7,
						0.5,
						10,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 0, 2.5],
							0,
						],
						12,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 2, 6],
							0.7,
						],
						14,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 5, 8],
							3,
						],
						16,
						['match', ['get', 'class'], ['motorway'], 10, 4],
						20,
						['match', ['get', 'class'], ['motorway'], 26, 17],
					],
					'line-opacity': 1,
				},
				metadata: {},
				filter: [
					'all',
					['!=', 'brunnel', 'tunnel'],
					['==', 'class', 'motorway'],
				],
			},
			{
				id: 'Minor road',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 10,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 100%)',
					'line-width': [
						'interpolate',
						['linear', 2],
						['zoom'],
						10,
						1,
						12,
						[
							'match',
							['get', 'class'],
							['tertiary'],
							1.5,
							['minor', 'service', 'track'],
							0.5,
							0.7,
						],
						14,
						[
							'match',
							['get', 'class'],
							['tertiary'],
							3,
							['minor', 'service', 'track'],
							1,
							1,
						],
						16,
						[
							'match',
							['get', 'class'],
							['tertiary'],
							6,
							['minor', 'service', 'track'],
							2,
							2,
						],
						20,
						[
							'match',
							['get', 'class'],
							['tertiary'],
							24,
							['minor', 'service', 'track'],
							12,
							12,
						],
					],
				},
				metadata: {},
				filter: [
					'all',
					['!=', 'brunnel', 'tunnel'],
					[
						'!in',
						'class',
						'aerialway',
						'bridge',
						'ferry',
						'minor_construction',
						'motorway',
						'motorway_construction',
						'path',
						'pier',
						'primary',
						'primary_construction',
						'rail',
						'secondary',
						'secondary_construction',
						'service_construction',
						'tertiary_construction',
						'track_construction',
						'transit',
						'trunk',
						'trunk_construction',
					],
				],
			},
			{
				id: 'Major road',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 6,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(48, 100%, 83%)',
					'line-width': [
						'interpolate',
						['linear', 2],
						['zoom'],
						6,
						['match', ['get', 'class'], 'trunk', 1, 0],
						10,
						['match', ['get', 'class'], ['trunk', 'primary'], 1.5, 1],
						12,
						['match', ['get', 'class'], ['trunk'], 2.5, ['primary'], 2.5, 1.5],
						14,
						['match', ['get', 'class'], ['trunk'], 3, ['primary'], 5, 4],
						16,
						['match', ['get', 'class'], ['trunk', 'primary'], 4, 4],
						20,
						['match', ['get', 'class'], ['trunk', 'primary'], 24, 24],
					],
				},
				metadata: {},
				filter: [
					'all',
					['!=', 'brunnel', 'tunnel'],
					['in', 'class', 'primary', 'secondary', 'trunk'],
				],
			},
			{
				id: 'Highway',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 4,
				layout: {
					'line-cap': 'butt',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(34, 100%, 77%)',
					'line-width': [
						'interpolate',
						['linear', 2],
						['zoom'],
						5,
						0.5,
						6,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'brunnel'], ['bridge'], 0, 1],
							0,
						],
						10,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 0, 2.5],
							1,
						],
						12,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 1, 4],
							0.7,
						],
						14,
						[
							'match',
							['get', 'class'],
							['motorway'],
							['match', ['get', 'ramp'], 1, 5, 6],
							1,
						],
						16,
						['match', ['get', 'class'], ['motorway'], 8, 2],
						20,
						['match', ['get', 'class'], ['motorway'], 24, 12],
					],
					'line-opacity': 1,
				},
				metadata: {},
				filter: [
					'all',
					['!=', 'brunnel', 'tunnel'],
					['==', 'class', 'motorway'],
				],
			},
			{
				id: 'Path',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 12,
				layout: {
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': {
						stops: [
							[6, 'hsl(0, 0%, 60%)'],
							[18, 'hsl(0, 0%, 51%)'],
						],
					},
					'line-width': {
						base: 1.2,
						stops: [
							[14, 0.5],
							[22, 3],
						],
					},
					'line-dasharray': [3, 2],
				},
				metadata: {},
				filter: [
					'all',
					['==', '$type', 'LineString'],
					['!in', 'brunnel', 'tunnel'],
					['in', 'class', 'path', 'pedestrian'],
				],
			},
			{
				id: 'Major railway',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': {
						stops: [
							[8, 'hsl(0,0%,72%)'],
							[16, 'hsl(0,0%,70%)'],
						],
					},
					'line-width': {
						base: 1.4,
						stops: [
							[14, 0.4],
							[15, 0.75],
							[20, 2],
						],
					},
					'line-opacity': ['match', ['get', 'service'], 'yard', 0.5, 1],
				},
				filter: [
					'all',
					['!in', 'brunnel', 'tunnel'],
					['==', 'class', 'rail'],
					['!=', 'subclass', 'funicular'],
				],
			},
			{
				id: 'Major railway hatching',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0,0%,72%)',
					'line-width': {
						base: 1.4,
						stops: [
							[14.5, 0],
							[15, 3],
							[20, 8],
						],
					},
					'line-opacity': ['match', ['get', 'service'], 'yard', 0.5, 1],
					'line-dasharray': [0.2, 9],
				},
				filter: [
					'all',
					['!in', 'brunnel', 'tunnel'],
					['==', 'class', 'rail'],
					['!=', 'subclass', 'funicular'],
				],
			},
			{
				id: 'Minor railway',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0,0%,73%)',
					'line-width': {
						base: 1.4,
						stops: [
							[14, 0.4],
							[15, 0.75],
							[20, 2],
						],
					},
				},
				filter: ['in', 'subclass', 'tram', 'light_rail'],
			},
			{
				id: 'Minor railway hatching',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0,0%,73%)',
					'line-width': {
						base: 1.4,
						stops: [
							[14.5, 0],
							[15, 2],
							[20, 6],
						],
					},
					'line-dasharray': [0.2, 4],
				},
				filter: ['in', 'subclass', 'tram', 'light_rail'],
			},
			{
				id: 'Building',
				type: 'fill',
				source: 'maptiler_planet',
				'source-layer': 'building',
				minzoom: 13,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-color': 'hsl(37, 11%, 77%)',
					'fill-antialias': true,
					'fill-outline-color': 'hsl(39, 10%, 72%)',
				},
			},
			{
				id: 'Building 3D',
				type: 'fill-extrusion',
				source: 'maptiler_planet',
				'source-layer': 'building',
				minzoom: 14,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'fill-extrusion-base': {
						type: 'identity',
						property: 'render_min_height',
					},
					'fill-extrusion-color': 'hsl(36, 8%, 64%)',
					'fill-extrusion-height': {
						type: 'identity',
						property: 'render_height',
					},
					'fill-extrusion-opacity': 0.5,
				},
				metadata: {},
			},
			{
				id: 'Minor lift',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 13,
				layout: {
					'line-cap': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 60%)',
					'line-width': {
						base: 1,
						stops: [
							[11, 1],
							[19, 2.5],
						],
					},
				},
				filter: [
					'all',
					['==', '$type', 'LineString'],
					['==', 'class', 'aerialway'],
					['!in', 'subclass', 'cable_car', 'funicular', 'gondola'],
				],
			},
			{
				id: 'Minor lift dash',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 13,
				layout: {
					'line-cap': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 60%)',
					'line-width': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						11,
						3,
						19,
						6,
					],
					'line-dasharray': [0.05, 3],
				},
				filter: [
					'all',
					['==', '$type', 'LineString'],
					['==', 'class', 'aerialway'],
					['!in', 'subclass', 'cable_car', 'funicular', 'gondola'],
				],
			},
			{
				id: 'Cable car',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 13,
				layout: {
					'line-cap': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 60%)',
					'line-width': {
						base: 1,
						stops: [
							[11, 1],
							[19, 2.5],
						],
					},
				},
				filter: [
					'all',
					['==', '$type', 'LineString'],
					['in', 'subclass', 'cable_car', 'funicular', 'gondola'],
				],
			},
			{
				id: 'Cable car dash',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'transportation',
				minzoom: 13,
				layout: {
					'line-cap': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 60%)',
					'line-width': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						11,
						3,
						19,
						5,
					],
					'line-dasharray': [2, 3],
				},
				filter: [
					'all',
					['==', '$type', 'LineString'],
					['in', 'subclass', 'cable_car', 'funicular', 'gondola'],
				],
			},
			{
				id: 'Aerialway labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'transportation_name',
				minzoom: 14,
				layout: {
					'text-font': ['Roboto Italic', 'Noto Sans Italic'],
					'text-size': {
						base: 1,
						stops: [
							[13, 10],
							[14, 11],
							[18, 13],
							[22, 15],
						],
					},
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-anchor': 'center',
					'text-offset': [0, 0.15],
					'text-justify': 'center',
					'text-optional': false,
					'text-max-width': 10,
					'symbol-placement': 'line',
					'icon-keep-upright': false,
					'icon-allow-overlap': false,
					'text-allow-overlap': false,
					'icon-ignore-placement': false,
					'text-ignore-placement': false,
				},
				paint: {
					'icon-color': 'hsl(0, 0%, 12%)',
					'text-color': 'hsl(0, 0%, 35%)',
					'text-halo-blur': 0,
					'text-halo-color': 'hsl(0,0%,100%)',
					'text-halo-width': 1.5,
				},
				filter: ['==', 'class', 'aerialway'],
			},
			{
				id: 'Other border',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'boundary',
				minzoom: 3,
				layout: {
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 60%)',
					'line-width': {
						stops: [
							[3, 0.75],
							[4, 1.25],
							[11, 1.75],
							[18, 2],
						],
					},
					'line-dasharray': [2, 1],
				},
				filter: [
					'all',
					['in', 'admin_level', 3, 4, 5, 6, 7, 8, 9, 10],
					['==', 'maritime', 0],
				],
			},
			{
				id: 'Disputed border',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'boundary',
				minzoom: 0,
				layout: {
					'line-cap': 'round',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 53%)',
					'line-width': {
						stops: [
							[1, 0.5],
							[5, 1.5],
							[10, 2],
						],
					},
					'line-dasharray': [2, 2],
				},
				filter: [
					'all',
					['==', 'admin_level', 2],
					['==', 'disputed', 1],
					['==', 'maritime', 0],
				],
			},
			{
				id: 'Country border',
				type: 'line',
				source: 'maptiler_planet',
				'source-layer': 'boundary',
				minzoom: 0,
				layout: {
					'line-cap': 'round',
					'line-join': 'round',
					visibility: 'visible',
				},
				paint: {
					'line-color': 'hsl(0, 0%, 45%)',
					'line-width': {
						stops: [
							[1, 0.5],
							[5, 1],
							[10, 2],
						],
					},
				},
				filter: [
					'all',
					['==', 'admin_level', 2],
					['==', 'disputed', 0],
					['==', 'maritime', 0],
				],
			},
			{
				id: 'River labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'waterway',
				minzoom: 13,
				layout: {
					'text-font': ['Roboto Italic', 'Noto Sans Italic'],
					'text-size': {
						stops: [
							[13, 10],
							[16, 14],
						],
					},
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'symbol-spacing': 350,
					'text-max-width': 5,
					'symbol-placement': 'line',
					'text-letter-spacing': 0.1,
					'text-rotation-alignment': 'map',
				},
				paint: {
					'text-color': 'hsl(213, 56%, 32%)',
					'text-halo-blur': 0.5,
					'text-halo-color': 'hsla(197, 87%, 88%, 0.6)',
					'text-halo-width': 1,
				},
				filter: ['has', 'name'],
			},
			{
				id: 'Lakeline labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'water_name',
				minzoom: 0,
				layout: {
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': 12,
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-max-width': 5,
					'symbol-placement': 'line',
				},
				paint: {
					'text-color': 'hsl(200, 88%, 26%)',
					'text-halo-color': 'hsla(0, 0%, 100%, 0.45)',
					'text-halo-width': 1.5,
				},
				metadata: {},
				filter: ['all', ['==', '$type', 'LineString']],
			},
			{
				id: 'Ocean labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'water_name',
				minzoom: 0,
				layout: {
					'text-font': ['Roboto Italic', 'Noto Sans Italic'],
					'text-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						1,
						13,
						3,
						17,
						9,
						17,
						14,
						25,
					],
					'text-field': '{name:en}',
					visibility: 'visible',
					'text-max-width': 5,
					'text-transform': 'none',
					'symbol-placement': 'point',
				},
				paint: {
					'text-color': {
						stops: [
							[1, 'hsl(206, 30%, 40%)'],
							[4, 'hsl(201, 28%, 34%)'],
							[6, 'hsl(207, 31%, 28%)'],
						],
					},
					'text-opacity': 1,
					'text-halo-blur': 1,
					'text-halo-color': {
						stops: [
							[1, 'hsla(200,72%,70%,0.05)'],
							[3, 'hsla(200,72%,70%,0.5)'],
						],
					},
					'text-halo-width': 1,
				},
				metadata: {},
				filter: ['all', ['has', 'name'], ['==', 'class', 'ocean']],
			},
			{
				id: 'Sea labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'water_name',
				minzoom: 3,
				layout: {
					'text-font': ['Roboto Italic', 'Noto Sans Italic'],
					'text-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						1,
						10,
						3,
						13,
						9,
						17,
						14,
						20,
					],
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-max-width': 5,
					'text-transform': 'none',
					'symbol-placement': 'point',
				},
				paint: {
					'text-color': {
						stops: [
							[1, 'hsl(206, 30%, 40%)'],
							[4, 'hsl(201, 28%, 34%)'],
							[6, 'hsl(207, 31%, 28%)'],
						],
					},
					'text-opacity': 1,
					'text-halo-blur': 1,
					'text-halo-color': {
						stops: [
							[1, 'hsla(200,72%,70%,0.05)'],
							[3, 'hsla(200,72%,70%,0.5)'],
						],
					},
					'text-halo-width': 1,
				},
				metadata: {},
				filter: ['all', ['has', 'name'], ['==', 'class', 'sea']],
			},
			{
				id: 'Lake labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'water_name',
				minzoom: 7,
				layout: {
					'text-font': ['Roboto Italic', 'Noto Sans Italic'],
					'text-size': 12,
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-max-width': 5,
				},
				paint: {
					'text-color': 'hsl(200, 88%, 26%)',
					'text-halo-color': 'hsla(0, 0%, 100%, 0.45)',
					'text-halo-width': 1.5,
				},
				metadata: {},
				filter: ['all', ['==', '$type', 'Point'], ['in', 'class', 'lake']],
			},
			{
				id: 'Road labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'transportation_name',
				layout: {
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': {
						base: 1,
						stops: [
							[13, 10],
							[14, 11],
							[18, 13],
							[22, 15],
						],
					},
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-anchor': 'center',
					'text-offset': [0, 0.15],
					'text-justify': 'center',
					'text-optional': false,
					'text-max-width': 10,
					'symbol-placement': 'line',
					'icon-keep-upright': false,
					'icon-allow-overlap': false,
					'text-allow-overlap': false,
					'icon-ignore-placement': false,
					'text-ignore-placement': false,
				},
				paint: {
					'icon-color': 'hsl(0, 0%, 12%)',
					'text-color': 'hsl(0, 0%, 12%)',
					'text-halo-blur': 0.5,
					'text-halo-color': 'hsl(0,0%,100%)',
					'text-halo-width': 1,
				},
				filter: ['!in', 'class', 'aerialway', 'ferry', 'service'],
			},
			{
				id: 'Volcano labels (US)',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'mountain_peak',
				minzoom: 9,
				layout: {
					'icon-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						9,
						['case', ['==', ['get', 'rank'], 1], 0.7, 0.5],
						14,
						['case', ['==', ['get', 'rank'], 1], 1, 0.8],
					],
					'text-font': ['Roboto Condensed Regular', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						7,
						9,
						11,
						10,
						13,
						13,
					],
					'icon-image': 'triangle',
					'text-field': [
						'concat',
						['coalesce', ['get', 'name:en'], ['get', 'name']],
						'\n',
						['get', 'ele_ft'],
						' ft',
					],
					visibility: 'visible',
					'text-anchor': 'top',
					'text-offset': [0, 0.7],
					'text-max-width': {
						stops: [
							[12, 4],
							[15, 4],
						],
					},
				},
				paint: {
					'icon-color': 'hsl(19, 91%, 45%)',
					'text-color': 'hsl(19, 91%, 45%)',
					'icon-halo-blur': ['interpolate', ['linear'], ['zoom'], 11, 2, 15, 0],
					'text-halo-blur': {
						stops: [
							[11, 2],
							[15, 0],
						],
					},
					'icon-halo-color': 'hsl(0, 0%, 100%)',
					'icon-halo-width': 1,
					'text-halo-color': 'hsl(0, 0%, 100%)',
					'text-halo-width': {
						stops: [
							[11, 1.6],
							[15, 1.3],
						],
					},
				},
				filter: [
					'all',
					['==', '$type', 'Point'],
					['in', 'class', 'volcano'],
					['has', 'name'],
					['has', 'customary_ft'],
				],
			},
			{
				id: 'Volcano labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'mountain_peak',
				minzoom: 9,
				layout: {
					'icon-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						9,
						['case', ['==', ['get', 'rank'], 1], 0.7, 0.5],
						14,
						['case', ['==', ['get', 'rank'], 1], 1, 0.8],
					],
					'text-font': ['Roboto Condensed Regular', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						7,
						9,
						11,
						10,
						13,
						13,
					],
					'icon-image': 'triangle',
					'text-field': [
						'concat',
						['coalesce', ['get', 'name:en'], ['get', 'name']],
						'\n',
						['get', 'ele'],
						' m',
					],
					visibility: 'visible',
					'text-anchor': 'top',
					'text-offset': [0, 0.7],
					'text-max-width': {
						stops: [
							[12, 4],
							[15, 4],
						],
					},
				},
				paint: {
					'icon-color': 'hsl(19, 91%, 45%)',
					'text-color': 'hsl(19, 91%, 45%)',
					'icon-halo-blur': ['interpolate', ['linear'], ['zoom'], 11, 2, 15, 0],
					'text-halo-blur': {
						stops: [
							[11, 2],
							[15, 0],
						],
					},
					'icon-halo-color': 'hsl(0, 0%, 100%)',
					'icon-halo-width': 1,
					'text-halo-color': 'hsl(0, 0%, 100%)',
					'text-halo-width': {
						stops: [
							[11, 1.6],
							[15, 1.3],
						],
					},
				},
				filter: [
					'all',
					['==', '$type', 'Point'],
					['in', 'class', 'volcano'],
					['has', 'name'],
					['!has', 'customary_ft'],
				],
			},
			{
				id: 'Peak labels (US)',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'mountain_peak',
				minzoom: 9,
				layout: {
					'icon-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						9,
						['case', ['==', ['get', 'rank'], 1], 0.7, 0.5],
						14,
						['case', ['==', ['get', 'rank'], 1], 1, 0.8],
					],
					'text-font': ['Roboto Condensed Regular', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						7,
						9,
						11,
						10,
						13,
						13,
					],
					'icon-image': 'triangle',
					'text-field': [
						'concat',
						['coalesce', ['get', 'name:en'], ['get', 'name']],
						'\n',
						['get', 'ele_ft'],
						' ft',
					],
					visibility: 'visible',
					'text-anchor': 'top',
					'text-offset': [0, 0.7],
					'text-max-width': {
						stops: [
							[12, 4],
							[15, 4],
						],
					},
				},
				paint: {
					'icon-color': 'hsl(23, 57%, 24%)',
					'text-color': 'hsl(23, 57%, 24%)',
					'icon-halo-blur': ['interpolate', ['linear'], ['zoom'], 11, 2, 15, 0],
					'text-halo-blur': {
						stops: [
							[11, 2],
							[15, 0],
						],
					},
					'icon-halo-color': 'hsl(0, 0%, 100%)',
					'icon-halo-width': 1,
					'text-halo-color': 'hsl(0, 0%, 100%)',
					'text-halo-width': {
						stops: [
							[11, 1.6],
							[15, 1.3],
						],
					},
				},
				filter: [
					'all',
					['==', '$type', 'Point'],
					['in', 'class', 'peak'],
					['has', 'name'],
					['has', 'customary_ft'],
				],
			},
			{
				id: 'Peak labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'mountain_peak',
				minzoom: 9,
				layout: {
					'icon-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						9,
						['case', ['==', ['get', 'rank'], 1], 0.7, 0.5],
						14,
						['case', ['==', ['get', 'rank'], 1], 1, 0.8],
					],
					'text-font': ['Roboto Condensed Regular', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						7,
						9,
						11,
						10,
						13,
						13,
					],
					'icon-image': 'triangle',
					'text-field': [
						'concat',
						['coalesce', ['get', 'name:en'], ['get', 'name']],
						'\n',
						['get', 'ele'],
						' m',
					],
					visibility: 'visible',
					'text-anchor': 'top',
					'text-offset': [0, 0.7],
					'text-max-width': {
						stops: [
							[12, 4],
							[15, 4],
						],
					},
				},
				paint: {
					'icon-color': 'hsl(23, 57%, 24%)',
					'text-color': 'hsl(23, 57%, 24%)',
					'icon-halo-blur': ['interpolate', ['linear'], ['zoom'], 11, 2, 15, 0],
					'text-halo-blur': {
						stops: [
							[11, 2],
							[15, 0],
						],
					},
					'icon-halo-color': 'hsl(0, 0%, 100%)',
					'icon-halo-width': 1,
					'text-halo-color': 'hsl(0, 0%, 100%)',
					'text-halo-width': {
						stops: [
							[11, 1.6],
							[15, 1.3],
						],
					},
				},
				filter: [
					'all',
					['==', '$type', 'Point'],
					['in', 'class', 'peak'],
					['has', 'name'],
					['!has', 'customary_ft'],
				],
			},
			{
				id: 'Place labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'place',
				minzoom: 4,
				layout: {
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						3,
						11,
						8,
						13,
						11,
						[
							'match',
							['get', 'class'],
							[
								'suburb',
								'neighbourhood',
								'quarter',
								'hamlet',
								'isolated_dwelling',
							],
							9,
							'island',
							8,
							12,
						],
						16,
						[
							'match',
							['get', 'class'],
							[
								'suburb',
								'neighbourhood',
								'quarter',
								'hamlet',
								'isolated_dwelling',
							],
							15,
							'island',
							11,
							16,
						],
					],
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-anchor': 'center',
					'text-offset': [0, 0],
					'text-padding': 2,
					'text-max-width': ['match', ['get', 'class'], ['island'], 6, 8],
					'text-transform': [
						'match',
						['get', 'class'],
						['suburb', 'neighborhood', 'neighbourhood', 'quarter', 'island'],
						'uppercase',
						'none',
					],
					'text-letter-spacing': [
						'match',
						['get', 'class'],
						['suburb', 'neighborhood', 'neighbourhood', 'quarter', 'island'],
						0.2,
						0,
					],
				},
				paint: {
					'text-color': 'hsl(0,0%,20%)',
					'text-opacity': [
						'step',
						['zoom'],
						1,
						8,
						['match', ['get', 'class'], ['island'], 0, 1],
						9,
						['match', ['get', 'class'], ['island'], 1, 1],
					],
					'text-halo-blur': [
						'match',
						['get', 'class'],
						['suburb', 'neighborhood', 'neighbourhood', 'quarter'],
						0.5,
						1,
					],
					'text-halo-color': 'hsl(0,0%,100%)',
					'text-halo-width': [
						'match',
						['get', 'class'],
						['suburb', 'neighborhood', 'neighbourhood', 'quarter'],
						1,
						1.2,
					],
				},
				metadata: {},
				filter: [
					'!in',
					'class',
					'city',
					'continent',
					'country',
					'province',
					'state',
					'town',
					'village',
				],
			},
			{
				id: 'Village labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'place',
				minzoom: 9,
				layout: {
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						3,
						11,
						8,
						13,
						11,
						12,
						16,
						18,
					],
					'text-field': '{name}',
					visibility: 'visible',
					'text-anchor': 'center',
					'text-offset': [0, 0],
					'text-padding': 2,
					'text-max-width': 8,
					'text-transform': 'none',
					'text-letter-spacing': 0,
				},
				paint: {
					'text-color': 'hsl(0,0%,20%)',
					'text-opacity': 1,
					'text-halo-blur': 1,
					'text-halo-color': 'hsl(0,0%,100%)',
					'text-halo-width': 1.2,
				},
				metadata: {},
				filter: ['==', 'class', 'village'],
			},
			{
				id: 'Airport labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'aerodrome_label',
				minzoom: 8,
				layout: {
					'icon-size': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						8,
						['case', ['==', ['get', 'class'], 'other'], 0.5, 0.6],
						16,
						1,
					],
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						10,
						9,
						12,
						11,
						14,
						13,
					],
					'icon-image': [
						'match',
						['get', 'class'],
						'other',
						'airfield',
						'airport',
					],
					'text-field': [
						'step',
						['zoom'],
						' ',
						8.99,
						' ',
						9,
						['coalesce', ['get', 'iata'], ['get', 'icao'], ['get', 'name']],
						12,
						['get', 'name'],
					],
					visibility: 'visible',
					'icon-anchor': 'bottom',
					'icon-offset': [
						'interpolate',
						['linear'],
						['zoom'],
						9,
						[
							'match',
							['get', 'class'],
							'other',
							['literal', [0, 0]],
							['literal', [0, 0]],
						],
						12,
						[
							'match',
							['get', 'class'],
							'other',
							['literal', [0, 0]],
							['literal', [0, 0]],
						],
					],
					'text-anchor': 'top',
					'icon-padding': 2,
					'text-line-height': 1,
				},
				paint: {
					'icon-color': 'hsl(28, 81%, 14%)',
					'text-color': 'hsl(28, 81%, 14%)',
					'icon-opacity': [
						'step',
						['zoom'],
						1,
						8,
						['match', ['get', 'class'], ['international', 'regional'], 1, 0],
						11,
						1,
					],
					'text-opacity': [
						'step',
						['zoom'],
						1,
						8,
						['match', ['get', 'class'], ['international', 'regional'], 1, 0],
						11,
						1,
					],
					'text-halo-blur': 0.5,
					'icon-halo-color': 'hsl(0, 0%, 100%)',
					'icon-halo-width': 1,
					'text-halo-color': 'hsl(0, 100%, 100%)',
					'text-halo-width': 1,
				},
				metadata: {},
				filter: ['in', 'class', 'international', 'other', 'regional'],
			},
			{
				id: 'Protected area labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'park',
				minzoom: 9,
				maxzoom: 16,
				layout: {
					'text-font': ['Roboto Italic', 'Noto Sans Italic'],
					'text-size': ['interpolate', ['linear'], ['zoom'], 9, 11, 14, 14],
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-padding': {
						stops: [
							[6, 39],
							[14, 99],
						],
					},
					'symbol-spacing': 750,
					'symbol-sort-key': ['to-number', ['get', 'rank']],
					'text-letter-spacing': 0.1,
					'text-ignore-placement': false,
				},
				paint: {
					'icon-color': 'hsl(120, 11%, 25%)',
					'text-color': 'hsl(120, 11%, 25%)',
					'text-opacity': [
						'step',
						['zoom'],
						0,
						9,
						['case', ['==', ['get', 'rank'], 1], 1, 0],
						10,
						1,
					],
					'text-halo-blur': 1,
					'text-halo-color': 'hsla(0, 0%, 100%, 0.5)',
					'text-halo-width': 1,
				},
				filter: [
					'!in',
					'class',
					'aire_d’adhésion_de_parc_national',
					'parc_national',
					'narodni_park',
					'national_nature_park',
					'national_park',
					'nationalpark',
					'natural_parc',
					'národní_park',
					'národný_park',
					'ochranné_pásmo_národného_parku',
					'parc_naturel_national',
					'parc_național',
					'parco_nazionale',
					'parque_nacional',
					'национальный_парк',
				],
			},
			{
				id: 'Town labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'place',
				minzoom: 7,
				maxzoom: 16,
				layout: {
					'icon-size': [
						'interpolate',
						['exponential', 1],
						['zoom'],
						6,
						0.6,
						14,
						0.8,
					],
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						6,
						['case', ['<=', ['get', 'rank'], 12], 11, 10],
						9,
						['case', ['<=', ['get', 'rank'], 15], 13, 12],
						16,
						['case', ['<=', ['get', 'rank'], 15], 22, 20],
					],
					'icon-image': 'dot',
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-anchor': 'bottom',
					'text-offset': [0, -0.2],
					'icon-optional': false,
					'text-max-width': 8,
					'icon-allow-overlap': true,
				},
				paint: {
					'icon-color': 'hsl(0, 0%, 100%)',
					'text-color': 'hsl(0,0%,20%)',
					'icon-opacity': ['step', ['zoom'], 1, 12, 0],
					'icon-halo-blur': 0,
					'icon-halo-color': 'hsl(0, 0%, 0%)',
					'icon-halo-width': 1,
					'text-halo-color': 'hsla(0,0%,100%,0.8)',
					'text-halo-width': 1.2,
				},
				metadata: {},
				filter: ['==', 'class', 'town'],
			},
			{
				id: 'State labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'place',
				minzoom: 3,
				maxzoom: 9,
				layout: {
					'text-font': ['Roboto Regular', 'Noto Sans Regular'],
					'text-size': {
						stops: [
							[3, 7],
							[5, 8],
							[6, 11],
						],
					},
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-padding': 2,
					'text-max-width': 8,
					'text-transform': 'uppercase',
					'symbol-sort-key': ['to-number', ['get', 'rank']],
					'text-letter-spacing': 0.1,
				},
				paint: {
					'text-color': 'hsl(51,4%,36%)',
					'text-opacity': [
						'step',
						['zoom'],
						0,
						3,
						['case', ['<=', ['get', 'rank'], 1], 1, 0],
						5,
						['case', ['<=', ['get', 'rank'], 3], 1, 0],
						8,
						['case', ['==', ['get', 'rank'], 0], 0, 1],
					],
					'text-halo-blur': 1,
					'text-halo-color': 'hsla(0,0%,100%,0.75)',
					'text-halo-width': {
						stops: [
							[3, 0.6],
							[8, 1],
						],
					},
				},
				metadata: {},
				filter: [
					'all',
					['in', 'class', 'state', 'province'],
					['<=', 'rank', 6],
				],
			},
			{
				id: 'City labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'place',
				minzoom: 4,
				maxzoom: 16,
				layout: {
					'icon-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						6,
						['match', ['get', 'capital'], 2, 0.7, 0.6],
						14,
						['match', ['get', 'capital'], 2, 0.9, 0.7],
					],
					'text-font': ['Roboto Medium', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						4,
						['case', ['==', ['get', 'capital'], 2], 14, 12],
						8,
						['case', ['==', ['get', 'capital'], 2], 18, 14],
						12,
						['case', ['==', ['get', 'capital'], 2], 24, 18],
						16,
						['case', ['==', ['get', 'capital'], 2], 32, 26],
					],
					'icon-image': 'circle-dot',
					'text-field': '{name:en}',
					visibility: 'visible',
					'icon-anchor': 'top',
					'icon-offset': [
						'interpolate',
						['linear'],
						['zoom'],
						6,
						['literal', [0, -2]],
						14,
						['literal', [0, 0]],
					],
					'text-anchor': 'bottom',
					'text-offset': [0, 0],
					'text-padding': 2,
					'icon-optional': false,
					'text-max-width': 9,
					'symbol-sort-key': ['to-number', ['get', 'rank']],
					'text-line-height': 0.8,
				},
				paint: {
					'icon-color': 'hsl(0, 0%, 0%)',
					'text-color': 'hsl(0,0%,20%)',
					'icon-opacity': ['step', ['zoom'], 1, 13, 0],
					'icon-halo-color': 'hsla(0,0%,100%,0.8)',
					'icon-halo-width': 1.2,
					'text-halo-color': 'hsla(0,0%,100%,0.8)',
					'text-halo-width': 1.2,
				},
				metadata: {},
				filter: ['==', 'class', 'city'],
			},
			{
				id: 'National park labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'park',
				minzoom: 7,
				maxzoom: 11,
				layout: {
					'text-font': ['Roboto Italic', 'Noto Sans Italic'],
					'text-size': ['interpolate', ['linear'], ['zoom'], 9, 11, 11, 12],
					'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
					visibility: 'visible',
					'text-padding': {
						stops: [
							[6, 39],
							[14, 99],
						],
					},
					'symbol-spacing': 750,
					'text-transform': 'none',
					'text-letter-spacing': 0.1,
					'text-ignore-placement': false,
				},
				paint: {
					'icon-color': 'hsl(120, 11%, 19%)',
					'text-color': 'hsl(120, 11%, 19%)',
					'text-halo-blur': 1,
					'text-halo-color': 'hsla(0, 0%, 100%, 0.5)',
					'text-halo-width': 1,
				},
				filter: [
					'in',
					'class',
					'aire_d’adhésion_de_parc_national',
					'parc_national',
					'narodni_park',
					'national_nature_park',
					'national_park',
					'nationalpark',
					'natural_parc',
					'národní_park',
					'národný_park',
					'ochranné_pásmo_národného_parku',
					'parc_naturel_national',
					'parc_național',
					'parco_nazionale',
					'parque_nacional',
					'национальный_парк',
				],
			},
			{
				id: 'Country labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'place',
				minzoom: 1,
				maxzoom: 12,
				layout: {
					'text-font': ['Roboto Medium', 'Noto Sans Regular'],
					'text-size': [
						'interpolate',
						['linear', 1],
						['zoom'],
						0,
						8,
						1,
						10,
						4,
						['case', ['>', ['get', 'rank'], 2], 14, 17],
						8,
						['case', ['>', ['get', 'rank'], 2], 19, 23],
					],
					'text-field': '{name:en}',
					visibility: 'visible',
					'text-padding': 1,
					'text-max-width': {
						stops: [
							[1, 5],
							[5, 8],
						],
					},
					'text-transform': 'none',
					'text-allow-overlap': false,
					'text-letter-spacing': 0.07,
				},
				paint: {
					'text-color': 'hsl(50, 7%, 18%)',
					'text-opacity': [
						'interpolate',
						['linear', 1],
						['zoom'],
						4,
						['case', ['>', ['get', 'rank'], 4], 0, 1],
						5.9,
						['case', ['>', ['get', 'rank'], 4], 0, 1],
						6,
						['case', ['>', ['get', 'rank'], 4], 1, 1],
					],
					'text-halo-blur': 1,
					'text-halo-color': 'hsl(0,0%,100%)',
					'text-halo-width': 0.8,
				},
				metadata: {},
				filter: ['all', ['==', 'class', 'country'], ['has', 'iso_a2']],
			},
			{
				id: 'Continent labels',
				type: 'symbol',
				source: 'maptiler_planet',
				'source-layer': 'place',
				maxzoom: 1,
				layout: {
					'text-font': ['Roboto Medium', 'Noto Sans Regular'],
					'text-size': {
						stops: [
							[0, 12],
							[2, 13],
						],
					},
					'text-field': '{name:en}',
					visibility: 'visible',
					'text-justify': 'center',
					'text-transform': 'uppercase',
				},
				paint: {
					'text-color': 'hsl(90, 2%, 20%)',
					'text-halo-blur': 0.5,
					'text-halo-color': 'hsla(0,0%,100%,0.7)',
					'text-halo-width': 1,
				},
				metadata: {},
				filter: ['==', 'class', 'continent'],
			},
		],
		glyphs: `https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key=${key}`,
		sprite: 'https://api.maptiler.com/maps/topo-v2/sprite',
		bearing: 0,
		pitch: 0,
		center: [0, 0],
		zoom: 1,
	}
}
